name: Compile Monorepo Vite Apps

on:
  push:
    branches: ["main"]
    paths:
      - "html-css/prism-js/v1/**"
      # Exclude the dist folder itself from triggering an infinite loop
      - "!html-css/prism-js/v1/dist/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: "html-css/prism-js/v1/package-lock.json"

      - name: Install and Build Vite App
        run: |
          npm ci
          npm run build
        working-directory: html-css/prism-js/v1

      - name: Commit and Push Built Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automated production build [skip ci]"
          file_pattern: "html-css/prism-js/v1/dist/**"
